<a href="https://colab.research.google.com/github/Vedullapalli-Asritha/Books-Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy 

Numpy stands for Numerical Python

In [ ]:
import numpy as np

to create an array

In [ ]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
sample_matrix=np.array(list_of_lists)

In [ ]:
sample_matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1,15)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.random.rand(3,2)

array([[0.36112046, 0.68287728],
       [0.7813115 , 0.09565832],
       [0.42130635, 0.18768447]])

In [28]:
np.random.randn(3,2)

array([[ 0.38561192, -0.0696971 ],
       [ 0.12374271,  0.7665172 ],
       [ 0.71923729,  0.60160004]])

In [29]:
np.random.randint(1,5)

2

In [ ]:
np.random.randint(34,100,50)

In [21]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
rand_array=np.random.randint(0,100,20)
rand_array

array([91,  9, 30, 31, 21, 43, 95,  5, 35, 63, 81, 15, 96, 99, 21, 87, 55,
       42, 77, 23])

In [24]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [25]:
rand_array.min()

5

to get the index of min val

In [22]:
rand_array.argmin()

7

In [34]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
a=np.random.rand(2,3)
a

array([[0.41125466, 0.11218504, 0.63023686],
       [0.64941059, 0.63116375, 0.92693856]])

In [37]:
a.T

array([[0.41125466, 0.64941059],
       [0.11218504, 0.63116375],
       [0.63023686, 0.92693856]])

In [38]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [39]:
sample_array[3]

13

In [41]:
sample_array[3:7]

array([13, 14, 15, 16])

In [53]:
sample_array[1:4]=100
sample_array

array([1001,  100,  100,  100, 1001, 1001, 1001,   17,   18,   19,   20])

In [43]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [45]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [46]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

Two-Dimensional array

In [47]:
import numpy as np

In [48]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [49]:
sample_matrix[0:2,2]

array([ 1, 21])

In [50]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [51]:
sample_matrix[2]

array([56, 76, 24,  7])

In [52]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [54]:
sample_array=np.arange(1,20)

In [55]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [57]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [58]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [59]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [60]:
np.min(sample_array)

1

In [61]:
np.max(sample_array)

19

In [62]:
np.argmin(sample_array)

0

In [63]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [67]:
np.std(sample_array)

5.477225575051661

In [68]:
np.var(sample_array)

30.0

In [69]:
np.mean(sample_array)

10.0

In [70]:
array=np.random.randn(3,4)
array

array([[ 1.92365435,  0.01199937,  0.70222044, -1.00189894],
       [ 1.25207472,  1.09245808,  0.34617958, -1.15721918],
       [-0.26397897,  1.62971173, -1.23850602, -1.01523987]])

In [71]:
np.round(array,decimals=3)

array([[ 1.924,  0.012,  0.702, -1.002],
       [ 1.252,  1.092,  0.346, -1.157],
       [-0.264,  1.63 , -1.239, -1.015]])

In [72]:
sports=np.array(['golf','cricket','fball','cricket','fball'])
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

pandas->To create data,create table,manipulation